### PR TITLE
[ge_ka]Use direction when address is not a street address

### PR DESCRIPTION
**Pull request by lokal-profil**
Last pass on Georgia.

* New [matches preview](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/matches&oldid=572798391)
* New [examples preiew](https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/preview&oldid=568971388)

Task: [T177077](https://phabricator.wikimedia.org/T177077)

### CODE REVIEW

**Comment by Vesihiisi** [comment]
Updated preview using current code: https://www.wikidata.org/w/index.php?title=Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/preview&oldid=568961226

**Comment by lokal-profil** [comment]
I'll add something to make use of wikilinked names

**Comment by lokal-profil** [comment]
Updated the matches table (no new matches survived blacklist)

**Comment by lokal-profil** [comment]
Fixed an error and it now gives [a longer list](https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/matches). Many of these will need to be blacklisted. E.g. biblical person, political party...

**Comment by lokal-profil** [comment]
Reverted using the name field for matching due to the low quality of the matches.

**Comment by lokal-profil** [comment]
@Vesihiisi If this last version works for you then approve and I'll put together a bot request

**Pull request merged**
