### PR TITLE
Base code for Georgia

### PR DESCRIPTION
**Pull request by lokal-profil**
Mapping: [Wikidata:WikiProject WLM/Mapping tables/ge (ka)](https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka))
Preview: [Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/preview](https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/ge_(ka)/preview)

Task: [T175337](https://phabricator.wikimedia.org/T175337)

### CODE REVIEW

**Comment by lokal-profil** [comment]
* Pinged about more mappings.
* Added districts file. Note that some don't have Georgian names because they are not recognized by Georgia.

**Comment by lokal-profil** [comment]
Can you then drop `georgia_districts.json` from the repo?

**Comment by lokal-profil** [comment]
Looks good to me

**Comment by lokal-profil** [comment]
Hum. We may have to extend the admin json with any P31:Q13220372 as well

**Comment by Vesihiisi** [comment]
Updated the admin mapping file. it's currently based on [this query](https://query.wikidata.org/#%23Cats%0ASELECT%20%3Fitem%20%3FitemLabel%20%0AWHERE%20%0A%7B%0A%20%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ2655841.%7D%0A%20%20UNION%0A%20%20%20%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ13220372.%7D%0A%20%20UNION%0A%20%20%7B%3Fitem%20wdt%3AP31%20wd%3AQ149621.%7D%0A%20%20%7B%3Fitem%20wdt%3AP17%20wd%3AQ230%7D%20UNION%20%7B%3Fitem%20wdt%3AP17%20wd%3AQ23334%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22ka%22.%20%7D%0A%7D).

**Pull request merged**
