### PR TITLE
Extending blacklist based on BO, SV and PA matches

### PR DESCRIPTION
**Pull request by lokal-profil**
BO: https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/bo_(es)/matches
SV: https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/sv_(es)/matches 
PA: https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/pa_(es)/matches

None added for Salvador

Task: [T179559](https://phabricator.wikimedia.org/T179559)
Task: [T179576](https://phabricator.wikimedia.org/T179576)

### CODE REVIEW

**Comment by Vesihiisi** [comment]
central bank (Q66344), on principle, yes or no?

**Comment by Vesihiisi** [comment]
And actually, in this particular case (Bolivia), the object is _Biblioteca Banco Central de Bolivia_, so not even the actual bank (has the bank as `monument_article`).

**Comment by Vesihiisi** [comment]
Some people have bad `monument_article` habits

**Comment by lokal-profil** [comment]
In general I would say allow central bank (we allow both _bank_ and the equivalent _national museum_).

My hack for Bolivia is [Q42562854](https://www.wikidata.org/wiki/Q42562854)

**Pull request merged**
