### PR TITLE
Chile

### PR DESCRIPTION
**Pull request by Vesihiisi**
mapping: https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/cl_(es)
preview: https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/cl_(es)/preview

Task: [T174330](https://phabricator.wikimedia.org/T174330)

### CODE REVIEW

**Comment by lokal-profil** [comment]
was there not a third heritage type? Could you use the more specific type of tipo to set the descriptions?

**Comment by Vesihiisi** [comment]
re: general comment. The third heritage type is natural monuments, i.e. reserves. While they are a subcategory of the same protection scheme, I don't think they should be counted as cultural heritage monuments.

**Comment by lokal-profil** [comment]
Preview updated to here. Ready to be checked

**Comment by lokal-profil** [comment]
[Matches](https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/cl_(es)/matches) ready

**Comment by lokal-profil** [comment]
Matches updated

**Comment by Vesihiisi** [comment]
Looked at preview and matches, all look ok.

**Pull request merged**
