### PR TITLE
More compact matches_preview

### PR DESCRIPTION
**Pull request by lokal-profil**
The previous format produced tables which quickly surpassed the
allowed number of Lua calls on a page. This solution is more
resource demanding during a run but should produce a less demanding
output.

### CODE REVIEW

**Comment by lokal-profil** [comment]
Not ready for review yet. awaiting a successful run to see if anything else is needed.

**Comment by lokal-profil** [comment]
The new format can be seen at [Mapping_tables/ir_(fa)/matches](https://www.wikidata.org/wiki/Wikidata:WikiProject_WLM/Mapping_tables/ir_(fa)/matches)

**Comment by Vesihiisi** [comment]
Is this ready for review then? Since the output looks super nice :D

**Comment by lokal-profil** [comment]
Yes, sorry that I forgot to tag you

**Pull request merged**
