### PR TITLE
Create a new WD item when encountering page without one

### PR DESCRIPTION
**Pull request by Vesihiisi**
When the data item is connected to a WP article without a Wikidata item, create one automatically.

Task: https://phabricator.wikimedia.org/T161711

### CODE REVIEW

**Comment by lokal-profil** [comment]
Wds must be instantiated (with a repo object) to be used.

**Comment by Vesihiisi** [comment]
Done.

**Comment by lokal-profil** [comment]
Would be nice to pass it a repo/wds object but I'm ok with this.

**Comment by lokal-profil** [comment]
Would be nice to pass it a repo/wds object but that is #41 so I'm ok with this for now.

**Pull request merged**
